services:
  project1:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start"
    env_file:
      - ./env/project1.env
    expose:
      - "3001"
    volumes:
      - ./services/project1:/app
      - project1_node_modules:/app/node_modules

  project2:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start"
    env_file:
      - ./env/project2.env
    expose:
      - "3002"
    volumes:
      - ./services/project2:/app
      - project2_node_modules:/app/node_modules

  project3:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start"
    env_file:
      - ./env/project3.env
    expose:
      - "3003"
    volumes:
      - ./services/project3:/app
      - project3_node_modules:/app/node_modules

  gateway:
    image: nginx:1.27-alpine
    depends_on:
      - project1
      - project2
      - project3
    ports:
      - "4545:4545"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  project1_node_modules:
  project2_node_modules:
  project3_node_modules:
